config/routes.rb
Rails.application.routes.draw do

    # Allow signup for users
    resources :users, only: [:new, :create, :edit, :update]

    # Allow login/logout for users
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#logout'

    # Allow access to home page
    get 'home', to: 'home#index'

    get 'memberlist', to: 'memberlist#index'
    post 'memberlist', to: 'memberlist#update'
    get 'event_points', to: 'memberlist#event_points'
    put 'update_event_points', to: 'memberlist#update_event_points'
    
    get 'edit', to: 'users#edit'
    get 'change_password', to: 'users#change_password'
    put 'update_password', to: 'users#update_password'
    
    # Defines the start page of the application
    root 'home#index'

    get "/:page", to: "static#show"
end

app/controllers/memberlist_controller.rb
class MemberlistController < ApplicationController
    
    # Maps to a View
    def index
        @filter = session[:filtertype]
        @threshold = session[:threshold]
        @points = session[:points]
        @role = session[:role]

        if(session[:name] != nil)
            @searchList = session[:name].split(" ")
        else
            @searchList = []
        end
        
        getFilteredUsers
    end

    # Maps to a View
    def event_points
        @events = Event.all().order(:date)
    end
    
    def update
        if params[:filtertype] != nil
            session[:filtertype] = params[:filtertype]
        end
    
        session[:role] = params[:userrole]
        session[:threshold] = params[:threshold]
        session[:points] = params[:q].to_i
        session[:name] = params[:name]
        redirect_to memberlist_path
    end

    def getFilteredUsers
        case
        when @filter == "namefilter" && @searchList != []
            @users = User.where(firstName: @searchList).or(User.where(lastName: @searchList)).order(:firstName)
        when @filter == "rolefilter" && @role != nil
            @users = User.where(role: @role).order(:firstName)
        when @filter == "pointfilter" && @points != nil && @threshold != nil
            if @threshold == "above"
                @users = User.all().order(:firstName).select { |user| user_events(user.id).sum(&:points) > @points }
            else
                @users = User.all().order(:firstName).select { |user| user_events(user.id).sum(&:points) < @points }
            end
        else
            @users = User.order(:firstName)
        end

        if @users == nil
            @users = []
        end
    end

    def update_event_points
        event = Event.find(params[:event][:saved_event_id])
        if event.update(:points => params[:event]["event_points"].to_i)
            redirect_to event_points_path, :notice => 'Success!'
        end
    end
end

app/helpers/memberlist_helper.rb
module MemberlistHelper
end

app/views/memberlist/_eventlist.html.erb
<table summary="Event table">
    <tr class="header">
        <th class="edit-points__column">Title</th>
        <th class="edit-points__column">Date</th>
        <th class="edit-points__column">Mandatory</th>
        <th class="edit-points__column">Points</th>
    </tr>
</table>
<% @events.each do |event| %>
<%= form_for event, url: { :controller=> 'memberlist', :action=> 'update_event_points'}, html: { method:'put' } do |f| %>
<%= f.hidden_field :saved_event_id, value: event.id %>
<div>
    <%= f.label event.title, :class => 'edit-points__column' %>
    <%= f.label event.date, :class => 'edit-points__column' %>
    <%= f.label event.mandatory, :class => 'edit-points__column' %>
    <div style="display: inline-block">
        <%= f.text_field :event_points, value: event.points, :style => 'width: 96px; display: inline-block', :class => 'text-field' %>
        <%= f.submit "Save", data: { disable_with: false }, :style => 'width: 50px; display: inline-block', :class => '"btn btn-primary"' %>
    </div>
</div>
<% end %>
<% end %>

app/views/memberlist/_memberlist.html.erb
<table summary="User detail view">
    <tr class="header">
        <th>Name</th>
        <th>Points</th>
        <th>Role</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td><%=link_to(user.firstName + " "+ user.lastName, home_path(:id => user.id), :class => 'action show') %></td>
        <td><%= user_events(user.id).sum(&:points) %></td>
        <td><%= user.role.capitalize %></td>
        <td><%= link_to "Edit", edit_user_path(user), :class => 'action edit' %></td>
    </tr>
    <% end %>
</table>

app/views/memberlist/event_points.html.erb
<head>
    <% content_for :title, "PBE Member List" %>
    <nav class="navbar navbar-light bg-light navbar-fixed-top">
        <div class="navbar-header">
            <%= link_to home_path do %>
            <%= fa_icon "home", size: '3x', id: "home-icon" %>
            <% end %>
        </div>

        <h1>Professional Brotherhood of Engineers</h1>

        <div class="navbar-nav navbar-right">
            <%= button_to "Logout", logout_path, method: "delete", :class => "btn btn-primary" %>
        </div>
    </nav>
</head>

<h2>Edit Event Points</h2>

<%= link_to 'Return to User List', memberlist_path %>

<%= render 'eventlist', locals: { events: @events } %>

app/views/memberlist/index.html.erb
<head>
    <% content_for :title, "PBE Member List" %>
    <nav class="navbar navbar-light bg-light navbar-fixed-top">
        <div class="navbar-header">
            <%= link_to home_path do %>
            <%= fa_icon "home", size: '3x', id: "home-icon" %>
            <% end %>
        </div>

        <h1>Professional Brotherhood of Engineers</h1>

        <div class="navbar-nav navbar-right">
            <%= button_to "Logout", logout_path, method: "delete", :class => "btn btn-primary" %>
        </div>
    </nav>
</head>

<h2>User List</h2>

<%= link_to 'Edit Event Points', event_points_path %>

<%= form_with  do |filter|%>
<%= filter.label(:f, "Filter users by: ") %>
<%= filter.radio_button(:filtertype, "pointfilter", :checked => @filter =="pointfilter", :onclick => "document.getElementById('filterButton').click()") %>
<%= filter.label(:pointfilterlabel, "Number of Points") %>
<%= filter.radio_button(:filtertype, "namefilter", :checked => @filter =="namefilter", :onclick => "document.getElementById('filterButton').click()") %>
<%= filter.label(:namefilterlabel, "Name") %>
<%= filter.radio_button(:filtertype, "rolefilter", :checked => @filter =="rolefilter", :onclick => "document.getElementById('filterButton').click()") %>
<%= filter.label(:rolefilterlabel, "Role") %>
<%= filter.radio_button(:filtertype, "nofilter", :checked => @filter =="nofilter", :onclick => "document.getElementById('filterButton').click()") %>
<%= filter.label(:nofilterlabel, "Nothing") %>
<%= filter.submit("Filter", :id => 'filterButton', :style => "display: none;", :onclick=> "updateFilter") %>
<% end %>

<%if @filter =="namefilter"%>
<%= form_with do |form|%>
<%= form.label(:q, "Search For Users With the Name") %>
<%= form.text_field(:name, value: @searchList) %>
<%= form.submit("Search") %>
<% end %>

<%elsif @filter =="rolefilter"%>
<%= form_with do |form|%>
<%= form.label(:q, "Search For Users With The Role") %>
<%= form.radio_button(:userrole, "member", :checked => @role == "member") %>
<%= form.label(:userrole_member, "Member") %>
<%= form.radio_button(:userrole, "admin", :checked => @role == "admin") %>
<%= form.label(:userrole_admin, "Admin") %>
<%= form.submit("Search") %>
<% end %>

<%elsif @filter =="pointfilter"%>
<%= form_with do |form|%>
<%= form.label(:q, "Search For Users With Points") %>
<%= form.radio_button(:threshold, "above", :checked => @threshold =="above") %>
<%= form.label(:threshold_above, "Above") %>
<%= form.radio_button(:threshold, "below", :checked => @threshold =="below") %>
<%= form.label(:threshold_below, "Below") %>
<%= form.number_field(:q, value: @points) %>
<%= form.submit("Search") %>
<% end %>
<% end %>

<%= render 'memberlist', locals: { users: @users } %>