config/routes.rb
Rails.application.routes.draw do

    # Allow signup for users
    resources :users, only: [:new, :create, :edit, :update]

    # Allow login/logout for users
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#logout'

    # Allow access to home page
    get 'home', to: 'home#index'

    get 'memberlist', to: 'memberlist#index'
    post 'memberlist', to: 'memberlist#update'
    get 'event_points', to: 'memberlist#event_points'
    put 'update_event_points', to: 'memberlist#update_event_points'
    
    get 'edit', to: 'users#edit'
    get 'change_password', to: 'users#change_password'
    put 'update_password', to: 'users#update_password'
    
    # Defines the start page of the application
    root 'home#index'

    get "/:page", to: "static#show"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    helper_method :point_percentage
    
    # Display home page
    def index
        if (params.has_key?(:id))
            @user = User.find(params[:id])
        end

        if @user == nil
            @user = current_user
        end
    end

    def point_percentage(user_id)
        user_event_count = user_events(user_id, true).count.to_f
        mandatory_event_count = mandatory_events.count.to_f

        if user_event_count == 0 || mandatory_event_count == 0
            return 0
        end

        return user_event_count / mandatory_event_count
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <% content_for :title, "PBE Member Profile" %>
    <nav class="navbar navbar-light bg-light">
        <ul class="navbar-nav navbar"></ul>

        <h3>Professional Brotherhood of Engineers</h3>

        <div class="navbar-nav navbar-right">
            <%= button_to "Logout", logout_path, method: "delete", :class => "btn btn-primary" %>
        </div>
    </nav>
</head>


<body>
    <h2><%= @user.firstName %> <%= @user.lastName %> | <%= @user.role.capitalize %></h2>
    <% if current_user.id == @user.id %>
    <p class="standing" style="color:rgb(<%=point_percentage(@user.id) >= 0.5 ? "86,188,127" : "188,86,86"%>)"><%= point_percentage(@user.id) >= 0.5 ? "You are currently in good standing!" : "You are currently in poor standing." %></p>
    <% end %>

    <table summary="User detail view">
        <tr>
            <th class="indextable">Current Points</th>
            <td class="indextable"><%= user_events(@user.id).sum(&:points) %></td>
        </tr>
        <tr>
            <th class="indextable">Percent Attendance</th>
            <td class="indextable"><%=(point_percentage(@user.id) * 100).round%>%</td>
        </tr>
        <tr>
            <th class="indextable">Membership Eligibility</th>
            <td class="indextable"><%=point_percentage(@user.id) >= 0.5 ? "Eligible" : "Not eligible"%></td>
        </tr>
        <tr>
            <th class="indextable">Officer Eligibility</th>
            <td class="indextable"><%=point_percentage(@user.id) >= 0.8 ? "Eligible" : "Not eligible"%></td>
        </tr>
    </table>

    <div id="links">
        <% if current_user.id == @user.id %>
        <div style="display: inline-block;">
            <%= button_to "Edit Profile", edit_user_path(@user), :method => "get", :class => "btn btn-primary" %>
        </div>
        <% end %>

        <% if is_admin?%>
        <div style="display: inline-block;">
            <%= button_to "View All Users", memberlist_path, :method => "get", :style => "display: inline-block;", :class => "btn btn-primary" %>
        </div>
        <% end %>
    </div>

    <h3>Event Participation</h3>
    <table summary="Event view">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
        </tr>
        <% user_events(@user.id).each do |event| %>
        <tr>
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.date %></td>
        </tr>
        <% end %>
    </table>

</body>

</html>